const fs = require('fs')
let s = fs.readFileSync('src/pages/KodeAktivasiPage.jsx', 'binary')
s = s.replace(/dY"[\x80-\xff]*\s*Import Excel/g, 'Import Excel')
s = s.replace(/dY"[\x80-\xff]*\s*Import JSON/g, 'Import JSON')
s = s.replace(/dY"[\x80-\xff]*\s*Template Excel/g, 'Template Excel')
s = s.replace(/dY"[\x80-\xff]*\s*Export/g, 'Export')
s = s.replace(/dY\-[\x80-\xff]*\s*Cetak/g, 'Cetak')
s = s.replace(/dY"[\x80-\xff]*\s*Salin Semua/g, 'Salin Semua')
s = s.replace(/[\x80-\xff]+\s*Terbitkan Kode/g, 'Terbitkan Kode')
s = s.replace(/[\x80-\xff]+\s*Aktif/g, 'Aktif')
fs.writeFileSync('src/pages/KodeAktivasiPage.jsx', s, 'binary')
console.log('done')
