const fs = require('fs')
let s = fs.readFileSync('src/pages/KodeAktivasiPage.jsx', 'binary')
// replace all invalid/question emoji sequences with clean ASCII alternatives
s = s.replace(/>\?{3,} Export</g, '>Export Excel</')
s = s.replace(/>\?{3,} Import JSON</g, '>Import JSON</')
s = s.replace(/>\?{3,} Import Excel</g, '>Import Excel</')
s = s.replace(/>\?{3,} Template Excel</g, '>Template Excel</')
s = s.replace(/>\?{3,} Cetak</g, '>Cetak</')
s = s.replace(/>\?{3,} Salin Semua</g, '>Salin Semua</')
s = s.replace(/icon="\?{3,}"/g, 'icon="key"')
s = s.replace(/<p[^>]*>\?{3,} Belum Aktif<\/p>/g, '<p className="text-xs text-slate-500">Belum Aktif</p>')
s = s.replace(/<strong>\?{3,} Cara/g, '<strong>Cara')
// also strip any remaining dY" or dY- sequences (UTF-8 decoding artifacts)
s = s.replace(/dY"[\x80-\xff]*/g, '')
s = s.replace(/dY\-[\x80-\xff]*/g, '')
fs.writeFileSync('src/pages/KodeAktivasiPage.jsx', s, 'binary')
console.log('done3')
